### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by zachary62** [zachary62/WideTable#2]
Assumption that we don't deal with:
- [ ] Assume no column has name "s" "c" for semi-ring.

For visualization:
- [x] Design low-level primitive: highlight relation, edge... add label ...
- [x] Make the force around the whole box, not only the header box
- [x] Highlight attribute when selected, and dehighlight when clicked again/click somewhere else
- [x] Make attributes scrollable, so each relation doesn't occupy too much space
- [x] Better arrow. Single arrow with highlight class, for both directions. Larger detect box (may transparent)
- [x] Boundary detector: circle must be in the area. Texts can't be dragged out of the box.
- [x] Support texts for edges.
- [x] Test cases for selection/groupby expands test_cjt_spja.py

Immediate TODO:
- [x] Generate 10 MB TPC-DS dataset.
- [x] For Semi-ring, let's create three semi-ring: sum, count, average semi-ring. count only has c. sum only has s. average has both (so the same as variance semiring). sum and average semi-ring takes the relation and attribute name as input.
- [x] Check the many-to-many, many-to-one and one-to-many relationship between tables.
- [x] Let's remove the conception of the root. For calibration, it randomly picks a root.
- [x] Support selection. Add test case: we can add selection conditions to relations. The aggregation result from absorption will change to be the one with selection.
- [x] Support group-by. Also, have test cases.
- [x] For the join graph visualization, makes it like the one from powerBI/Looker. 
(https://datamonkeysite.com/2021/07/15/first-impression-of-looker/)
We want to have all the attributes in the table box. The edge shows the join key, cardinality, and whether missing values.
Maybe below is a better way to interact with notebook?
(https://livingwithmachines.ac.uk/d3-javascript-visualisation-in-a-python-jupyter-notebook/)
user register a bunch of attribute for semi-ring aggregation.
This is the visualization for cjt, not join graph because it contains semi-ring from cjt.
- [x] Another layer of indirection between the table name the user provides and the table name stored. This is essential to support many measurements.
- [x] Support removing attributes.
- [x] Use null message for multiplicity. Support normalized message.
- [x] Refactor the codes following MVC.
- [x] Simple visualization for the table. E.g., the preview of each table. Preview of the missing values...
- [x] Define the measurements through the HTML (have a sidebar that specifies the relation, the aggregation sum, count or average, the expression ). example of sidebar: https://vega.github.io/voyager/
- [x] Cookies to store current state. (let's use gitpod and don't set up server. Server can cause SQL injection)
- [x] When click on the edge, highlight the join keys.
- [x] Support attribution
- [ ] On the header of the table, small button to sort by this column on the explore view. Double click swap asc/dec.
- [ ] Allow user to construct query in the dashboard

Future TODO for Research:
- [ ] Support in/not in
- [ ] Support cyclic join graph, but acyclic join query
- [x] For invalidated messages, create a new message type: Missing. Initially, all edges had missing messages. Calibration computes all missing messages.
- [ ] Support remove table, add a table.
- [ ] Support IVM (Incremental View Maintenance)
- [ ] Build visualization for json and graph database-like. 
For table visualization, I think the graph below is clear, with attributes name below tables.
![image](https://user-images.githubusercontent.com/33015448/201497689-f288e6e8-4cfb-425b-b83d-9608e7a26865.png)
https://d3-graph-gallery.com/dendrogram.html
https://d3-graph-gallery.com/bundle.html
https://d3-graph-gallery.com/network.html
- [ ] Support attribution.
- [x] Support duplication-aware message passing.
- [ ] Support causal inference.
- [ ] Support outer join.
